codecov:
  token: 3b97de67-4cff-47fc-b3ce-80ac799b552b
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches: null
        informational: true

    patch:
      default:
        target: auto
        branches: 1%
        informational: true

    changes:
      default:
        branches: null
        threshold: 1%
        informational: true


comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
